-- MySQL Script generated by MySQL Workbench
-- Tue Apr 24 21:29:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ioTireBouchon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ioTireBouchon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ioTireBouchon` DEFAULT CHARACTER SET utf8 ;
USE `ioTireBouchon` ;

-- -----------------------------------------------------
-- Table `ioTireBouchon`.`vol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ioTireBouchon`.`vol` (
  `idVol` INT NOT NULL AUTO_INCREMENT,
  `nomVol` VARCHAR(45) NULL,
  `nomPilote` VARCHAR(45) NULL,
  `dateVol` DATE NULL,
  `dureDuVol` REAL NULL,
  `batterieLife` INT NULL,
  `puissanceMoteur` INT NULL,
  PRIMARY KEY (`idVol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ioTireBouchon`.`map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ioTireBouchon`.`map` (
  `idMap` INT NOT NULL AUTO_INCREMENT,
  `nomMap` VARCHAR(45) NULL,
  `dateMapGenere` VARCHAR(45) NULL,
  `vol_idVol` INT NOT NULL,
  PRIMARY KEY (`idMap`, `vol_idVol`),
  INDEX `fk_map_vol1_idx` (`vol_idVol` ASC),
  CONSTRAINT `fk_map_vol1`
    FOREIGN KEY (`vol_idVol`)
    REFERENCES `ioTireBouchon`.`vol` (`idVol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ioTireBouchon`.`point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ioTireBouchon`.`point` (
  `idPoint` INT NOT NULL AUTO_INCREMENT,
  `longitude` FLOAT NOT NULL,
  `latitude` FLOAT NULL,
  `hauteur` FLOAT NULL,
  `map_idMap` INT NOT NULL,
  PRIMARY KEY (`idPoint`),
  INDEX `fk_point_map_idx` (`map_idMap` ASC),
  CONSTRAINT `fk_point_map`
    FOREIGN KEY (`map_idMap`)
    REFERENCES `ioTireBouchon`.`map` (`idMap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
